services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: unless-stopped
    ports:
      - '2368:3001'
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    environment:
      - url=http://localhost:2368
    depends_on:
      - npm

volumes:
  data:
    driver: local
  letsencrypt:
    driver: local
  ghost:
    driver: local