services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      tele-net:
        ipv4_address: 10.0.0.2
    env_file:
      - .env

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: unless-stopped
    # ports:
    #   - '3001:2368'
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    networks:
      tele-net:
        ipv4_address: 10.0.0.3
    environment:
      - url=http://localhost:2368
    env_file:
      - .env
    depends_on:
      - npm

volumes:
data:
letsencrypt:
ghost:
